-- ==============================================================================
-- FULL SUPABASE MIGRATION SCRIPT FOR JAZA SURVEYS
-- Project URL: https://kkmxfemeeuhtfuhjcith.supabase.co
-- Run this complete SQL script in your Supabase SQL Editor to set up all tables,
-- functions, triggers, security policies, and default seed data.
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. CLEANUP / RESET (SAFE FOR FRESH INITIALIZATION)
-- ------------------------------------------------------------------------------
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP FUNCTION IF EXISTS public.complete_survey(UUID, NUMERIC);

-- ------------------------------------------------------------------------------
-- 2. CREATE TABLES
-- ------------------------------------------------------------------------------

-- User Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  full_name TEXT,
  phone TEXT,
  avatar_url TEXT,
  balance NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
  total_earned NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
  total_withdrawn NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
  surveys_completed INTEGER DEFAULT 0 NOT NULL,
  surveys_pending INTEGER DEFAULT 0 NOT NULL,
  membership_tier TEXT DEFAULT 'Bronze' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Survey Categories Table
CREATE TABLE IF NOT EXISTS public.survey_categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  unlock_price NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
  earning_cap NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
  surveys_available INTEGER DEFAULT 0 NOT NULL,
  reward_per_survey NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
  icon TEXT DEFAULT 'Gift',
  gradient TEXT DEFAULT 'from-emerald-400 to-teal-600',
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  display_order INTEGER DEFAULT 0 NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Surveys Table
CREATE TABLE IF NOT EXISTS public.surveys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  category_id TEXT DEFAULT 'starter' NOT NULL,
  reward NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
  duration TEXT DEFAULT '5 min' NOT NULL,
  questions_count INTEGER DEFAULT 5 NOT NULL,
  premium BOOLEAN DEFAULT FALSE NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Survey Questions Table
CREATE TABLE IF NOT EXISTS public.survey_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id BIGINT REFERENCES public.surveys(id) ON DELETE CASCADE NOT NULL,
  question_text TEXT NOT NULL,
  options TEXT[] NOT NULL,
  question_order INTEGER DEFAULT 1 NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Survey Completions Table
CREATE TABLE IF NOT EXISTS public.survey_completions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  survey_id BIGINT REFERENCES public.surveys(id) ON DELETE CASCADE NOT NULL,
  reward_earned NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
  answers JSONB DEFAULT '{}'::jsonb NOT NULL,
  completed_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT unique_user_survey_completion UNIQUE (user_id, survey_id)
);

-- User Category Unlocks Table
CREATE TABLE IF NOT EXISTS public.user_category_unlocks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  category_id TEXT NOT NULL,
  unlocked_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  total_earned_in_category NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
  surveys_completed_in_category INTEGER DEFAULT 0 NOT NULL,
  payment_status TEXT DEFAULT 'completed' NOT NULL,
  mpesa_checkout_request_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT unique_user_category_unlock UNIQUE (user_id, category_id)
);

-- Withdrawals Table
CREATE TABLE IF NOT EXISTS public.withdrawals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  phone_number TEXT NOT NULL,
  status TEXT DEFAULT 'pending' NOT NULL, -- 'pending', 'processing', 'completed', 'failed'
  transaction_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- User Packages Table
CREATE TABLE IF NOT EXISTS public.user_packages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  package_type TEXT NOT NULL, -- 'bronze', 'silver', 'gold', 'platinum'
  price_paid NUMERIC(12, 2) NOT NULL,
  surveys_unlocked INTEGER DEFAULT 0 NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  purchased_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- M-Pesa Payments Table
CREATE TABLE IF NOT EXISTS public.mpesa_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  category_id TEXT,
  amount NUMERIC(12, 2) NOT NULL,
  phone_number TEXT NOT NULL,
  checkout_request_id TEXT NOT NULL,
  merchant_request_id TEXT,
  mpesa_receipt_number TEXT,
  status TEXT DEFAULT 'pending' NOT NULL, -- 'pending', 'processing', 'completed', 'failed'
  result_code INTEGER,
  result_desc TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ------------------------------------------------------------------------------
-- 3. INDEXES FOR PERFORMANCE
-- ------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_surveys_category_id ON public.surveys(category_id);
CREATE INDEX IF NOT EXISTS idx_survey_questions_survey_id ON public.survey_questions(survey_id);
CREATE INDEX IF NOT EXISTS idx_survey_completions_user_id ON public.survey_completions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_category_unlocks_user_id ON public.user_category_unlocks(user_id);
CREATE INDEX IF NOT EXISTS idx_mpesa_payments_checkout ON public.mpesa_payments(checkout_request_id);

-- ------------------------------------------------------------------------------
-- 4. FUNCTIONS & TRIGGERS
-- ------------------------------------------------------------------------------

-- Auto-create Profile Trigger Function
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, phone, balance, total_earned, total_withdrawn, surveys_completed, surveys_pending, membership_tier)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'phone', ''),
    0,
    0,
    0,
    0,
    0,
    'Bronze'
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(EXCLUDED.full_name, public.profiles.full_name),
    phone = COALESCE(EXCLUDED.phone, public.profiles.phone);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger execution on auth.users insert
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- RPC Function: complete_survey
CREATE OR REPLACE FUNCTION public.complete_survey(p_user_id UUID, p_reward NUMERIC)
RETURNS VOID AS $$
BEGIN
  UPDATE public.profiles
  SET 
    balance = balance + p_reward,
    total_earned = total_earned + p_reward,
    surveys_completed = surveys_completed + 1,
    updated_at = NOW()
  WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ------------------------------------------------------------------------------
-- 5. ROW LEVEL SECURITY (RLS) POLICIES
-- ------------------------------------------------------------------------------

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.surveys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.survey_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.survey_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_category_unlocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.survey_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mpesa_payments ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Allow public read access to profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow users to insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Allow users to update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Surveys Policies
CREATE POLICY "Allow public read access to surveys" ON public.surveys FOR SELECT USING (true);

-- Survey Questions Policies
CREATE POLICY "Allow public read access to survey questions" ON public.survey_questions FOR SELECT USING (true);

-- Survey Completions Policies
CREATE POLICY "Allow users to read their own completions" ON public.survey_completions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow users to insert their own completions" ON public.survey_completions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- User Category Unlocks Policies
CREATE POLICY "Allow users to read their own unlocks" ON public.user_category_unlocks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow users to insert their own unlocks" ON public.user_category_unlocks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow users to update their own unlocks" ON public.user_category_unlocks FOR UPDATE USING (auth.uid() = user_id);

-- Withdrawals Policies
CREATE POLICY "Allow users to read their own withdrawals" ON public.withdrawals FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow users to insert their own withdrawals" ON public.withdrawals FOR INSERT WITH CHECK (auth.uid() = user_id);

-- User Packages Policies
CREATE POLICY "Allow users to read their own packages" ON public.user_packages FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow users to insert their own packages" ON public.user_packages FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Survey Categories Policies
CREATE POLICY "Allow public read access to categories" ON public.survey_categories FOR SELECT USING (true);

-- M-Pesa Payments Policies
CREATE POLICY "Allow users to read their payments" ON public.mpesa_payments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow users to insert their payments" ON public.mpesa_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow users to update their payments" ON public.mpesa_payments FOR UPDATE USING (auth.uid() = user_id);

-- ------------------------------------------------------------------------------
-- 6. SEED DATA - CATEGORIES
-- ------------------------------------------------------------------------------
INSERT INTO public.survey_categories (id, name, description, unlock_price, earning_cap, surveys_available, reward_per_survey, icon, gradient, is_active, display_order)
VALUES
  ('starter', 'Free Starter', 'Complete free surveys and earn up to KSH 1,500', 0, 1500, 10, 150, 'Gift', 'from-emerald-400 to-teal-600', true, 1),
  ('bronze_plus', 'Bronze Plus', 'Unlock surveys earning up to KSH 1,000 more', 159, 1000, 8, 125, 'Zap', 'from-amber-600 to-orange-500', true, 2),
  ('silver_plus', 'Silver Plus', 'Unlock surveys earning up to KSH 2,500 more', 199, 2500, 15, 167, 'Award', 'from-slate-400 to-slate-600', true, 3),
  ('gold_plus', 'Gold Plus', 'Unlock surveys earning up to KSH 3,000 more', 229, 3000, 15, 200, 'Crown', 'from-yellow-400 to-yellow-600', true, 4),
  ('platinum_plus', 'Platinum Plus', 'Unlock surveys earning up to KSH 3,500 more', 259, 3500, 15, 234, 'Gem', 'from-cyan-400 to-blue-600', true, 5),
  ('diamond_plus', 'Diamond Plus', 'Unlock surveys earning up to KSH 5,000 more', 299, 5000, 20, 250, 'Diamond', 'from-violet-500 to-purple-700', true, 6)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  unlock_price = EXCLUDED.unlock_price,
  earning_cap = EXCLUDED.earning_cap,
  surveys_available = EXCLUDED.surveys_available,
  reward_per_survey = EXCLUDED.reward_per_survey;

-- ------------------------------------------------------------------------------
-- 7. SEED DATA - STARTER SURVEYS & QUESTIONS
-- ------------------------------------------------------------------------------
INSERT INTO public.surveys (title, reward, duration, questions_count, category, is_active, category_id) VALUES
('Kenya Consumer Shopping Habits', 115, '5 min', 6, 'Lifestyle', true, 'starter'),
('Mobile Money Usage Patterns', 118, '4 min', 5, 'Finance', true, 'starter'),
('Public Transport Preferences', 122, '3 min', 5, 'Transport', true, 'starter'),
('Food & Dining Preferences', 125, '4 min', 6, 'Lifestyle', true, 'starter'),
('Entertainment & Media Consumption', 128, '5 min', 6, 'Entertainment', true, 'starter'),
('Healthcare Access & Satisfaction', 132, '4 min', 5, 'Health', true, 'starter'),
('Education & Learning Preferences', 135, '5 min', 6, 'Education', true, 'starter'),
('Technology & Device Usage', 138, '3 min', 5, 'Technology', true, 'starter');

-- Starter Questions
INSERT INTO public.survey_questions (survey_id, question_text, options, question_order) VALUES
((SELECT id FROM public.surveys WHERE title = 'Kenya Consumer Shopping Habits' LIMIT 1), 'Where do you shop most often?', '{"Local markets","Supermarkets","Online stores","Malls","Small shops/kiosks"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Kenya Consumer Shopping Habits' LIMIT 1), 'How often do you go shopping?', '{"Daily","2-3 times a week","Weekly","Monthly","Less often"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Kenya Consumer Shopping Habits' LIMIT 1), 'What influences your buying decision most?', '{"Price","Quality","Brand","Recommendations","Advertisements"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Kenya Consumer Shopping Habits' LIMIT 1), 'Do you compare prices before buying?', '{"Always","Often","Sometimes","Rarely","Never"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Kenya Consumer Shopping Habits' LIMIT 1), 'What payment method do you prefer?', '{"Cash","M-Pesa","Credit/Debit card","Mobile banking","Credit from shop"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Kenya Consumer Shopping Habits' LIMIT 1), 'How much do you spend weekly on shopping?', '{"Under 500 KSH","500-1000 KSH","1000-2500 KSH","2500-5000 KSH","Over 5000 KSH"}', 6),

((SELECT id FROM public.surveys WHERE title = 'Mobile Money Usage Patterns' LIMIT 1), 'Which mobile money service do you use?', '{"M-Pesa","Airtel Money","TKash","Equitel","Multiple services"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Mobile Money Usage Patterns' LIMIT 1), 'How often do you use mobile money?', '{"Daily","Several times a week","Weekly","Monthly","Rarely"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Mobile Money Usage Patterns' LIMIT 1), 'What do you use mobile money for most?', '{"Sending money","Receiving money","Paying bills","Buying goods","Banking transactions"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Mobile Money Usage Patterns' LIMIT 1), 'Are you satisfied with transaction fees?', '{"Very satisfied","Satisfied","Neutral","Dissatisfied","Very dissatisfied"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Mobile Money Usage Patterns' LIMIT 1), 'Have you ever had issues with mobile money?', '{"Never","Rarely","Sometimes","Often","Very often"}', 5),

((SELECT id FROM public.surveys WHERE title = 'Public Transport Preferences' LIMIT 1), 'What transport do you use most?', '{"Matatu","Bus","Boda boda","Taxi/Uber","Personal car"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Public Transport Preferences' LIMIT 1), 'How much do you spend on transport daily?', '{"Under 100 KSH","100-200 KSH","200-500 KSH","500-1000 KSH","Over 1000 KSH"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Public Transport Preferences' LIMIT 1), 'Are you satisfied with public transport?', '{"Very satisfied","Satisfied","Neutral","Dissatisfied","Very dissatisfied"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Public Transport Preferences' LIMIT 1), 'What is your biggest transport concern?', '{"Cost","Safety","Time delays","Overcrowding","Route availability"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Public Transport Preferences' LIMIT 1), 'Would you use a ride-sharing app?', '{"Already do","Yes, definitely","Maybe","Probably not","No interest"}', 5),

((SELECT id FROM public.surveys WHERE title = 'Food & Dining Preferences' LIMIT 1), 'Where do you eat most often?', '{"Home cooked","Street food","Restaurants","Fast food","Hotel/Café"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Food & Dining Preferences' LIMIT 1), 'How often do you eat out?', '{"Daily","2-3 times a week","Weekly","Monthly","Rarely"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Food & Dining Preferences' LIMIT 1), 'What cuisine do you prefer?', '{"Kenyan traditional","Fast food","Indian","Chinese","Continental/Western"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Food & Dining Preferences' LIMIT 1), 'How much do you spend on a meal out?', '{"Under 200 KSH","200-500 KSH","500-1000 KSH","1000-2000 KSH","Over 2000 KSH"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Food & Dining Preferences' LIMIT 1), 'Do you use food delivery apps?', '{"Often","Sometimes","Rarely","Never","Didn''t know they exist"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Food & Dining Preferences' LIMIT 1), 'What matters most when dining out?', '{"Price","Taste","Hygiene","Location","Service quality"}', 6),

((SELECT id FROM public.surveys WHERE title = 'Entertainment & Media Consumption' LIMIT 1), 'How do you watch movies/shows most?', '{"TV","Cinema","Streaming services","Downloads","YouTube"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Media Consumption' LIMIT 1), 'What type of music do you listen to?', '{"Bongo/Genge","Gospel","International pop","Afrobeat","Reggae/Roots"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Media Consumption' LIMIT 1), 'How many hours of entertainment daily?', '{"Less than 1 hour","1-2 hours","2-4 hours","4-6 hours","Over 6 hours"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Media Consumption' LIMIT 1), 'Do you subscribe to any streaming service?', '{"Netflix","Showmax","Amazon Prime","YouTube Premium","None"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Media Consumption' LIMIT 1), 'What device do you use for entertainment?', '{"Smartphone","TV","Laptop","Tablet","Cinema"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Media Consumption' LIMIT 1), 'How much do you spend on entertainment monthly?', '{"Under 500 KSH","500-1000 KSH","1000-2500 KSH","2500-5000 KSH","Over 5000 KSH"}', 6),

((SELECT id FROM public.surveys WHERE title = 'Healthcare Access & Satisfaction' LIMIT 1), 'Where do you seek medical care most?', '{"Public hospital","Private hospital","Pharmacy","Clinic","Traditional healer"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Healthcare Access & Satisfaction' LIMIT 1), 'Do you have health insurance?', '{"NHIF","Private insurance","Both","None","Planning to get"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Healthcare Access & Satisfaction' LIMIT 1), 'How far is your nearest health facility?', '{"Walking distance","Under 5km","5-10km","10-20km","Over 20km"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Healthcare Access & Satisfaction' LIMIT 1), 'Are you satisfied with healthcare costs?', '{"Very satisfied","Satisfied","Neutral","Dissatisfied","Very dissatisfied"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Healthcare Access & Satisfaction' LIMIT 1), 'How often do you visit a doctor?', '{"Monthly","Every 3 months","Yearly","Only when sick","Rarely"}', 5),

((SELECT id FROM public.surveys WHERE title = 'Education & Learning Preferences' LIMIT 1), 'What is your highest education level?', '{"Primary","Secondary","Diploma","Degree","Postgraduate"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Education & Learning Preferences' LIMIT 1), 'Are you currently studying?', '{"Yes, full-time","Yes, part-time","Planning to","No, completed","No, stopped"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Education & Learning Preferences' LIMIT 1), 'How do you prefer to learn new skills?', '{"Online courses","In-person classes","Self-study","Videos/Tutorials","Workshops"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Education & Learning Preferences' LIMIT 1), 'Would you pay for an online course?', '{"Yes, definitely","Maybe, if affordable","Unsure","Probably not","No"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Education & Learning Preferences' LIMIT 1), 'What skills do you want to learn?', '{"Technology/Digital","Business/Finance","Creative arts","Languages","Professional skills"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Education & Learning Preferences' LIMIT 1), 'How much would you spend on a course?', '{"Under 1000 KSH","1000-5000 KSH","5000-15000 KSH","15000-50000 KSH","Over 50000 KSH"}', 6),

((SELECT id FROM public.surveys WHERE title = 'Technology & Device Usage' LIMIT 1), 'What smartphone do you use?', '{"Samsung","Tecno/Infinix/Itel","iPhone","Huawei/Xiaomi","Other/Feature phone"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Technology & Device Usage' LIMIT 1), 'How many hours daily on your phone?', '{"1-2 hours","3-4 hours","5-6 hours","7-8 hours","Over 8 hours"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Technology & Device Usage' LIMIT 1), 'What do you use your phone for most?', '{"Social media","Communication","Entertainment","Work/Business","News/Information"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Technology & Device Usage' LIMIT 1), 'Do you have internet at home?', '{"Yes, WiFi","Yes, mobile data","Both","No, use public WiFi","No internet access"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Technology & Device Usage' LIMIT 1), 'How much do you spend on data monthly?', '{"Under 500 KSH","500-1000 KSH","1000-2500 KSH","2500-5000 KSH","Over 5000 KSH"}', 5);

-- ------------------------------------------------------------------------------
-- 8. SEED DATA - BRONZE PLUS SURVEYS & QUESTIONS
-- ------------------------------------------------------------------------------
INSERT INTO public.surveys (title, category, category_id, reward, duration, questions_count, is_active, created_at) VALUES
('Online Shopping Preferences', 'Technology', 'bronze_plus', 150, '4 min', 8, true, NOW()),
('Mobile App Experience', 'Technology', 'bronze_plus', 150, '3 min', 8, true, NOW()),
('Digital Payment Methods', 'Finance', 'bronze_plus', 150, '4 min', 8, true, NOW()),
('Investment Awareness', 'Finance', 'bronze_plus', 150, '5 min', 8, true, NOW()),
('Tech Gadget Usage', 'Technology', 'bronze_plus', 150, '3 min', 8, true, NOW());

-- Questions for Bronze Plus Surveys
INSERT INTO public.survey_questions (survey_id, question_text, options, question_order) VALUES
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'How often do you shop online?', '{"Weekly","Bi-weekly","Monthly","Quarterly","Never"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'Which platform do you use most for online shopping?', '{"Jumia","Kilimall","Social Media (Instagram/Facebook)","Amazon","Other local e-commerce"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'What type of products do you buy online most?', '{"Electronics","Fashion & Clothing","Beauty & Personal Care","Groceries","Home & Kitchen"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'What is your primary reason for shopping online?', '{"Convenience","Better prices","Wider selection","Discounts/Promotions","Home delivery"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'What is your main concern when buying online?', '{"Product authenticity/quality","Delivery speed","Payment security","Return process","High delivery costs"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'How do you prefer to pay for online orders?', '{"M-Pesa / Mobile Money","Pay on Delivery (Cash)","Credit/Debit Card","Bank Transfer","Buy Now Pay Later"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'How much do you spend on online shopping monthly?', '{"Under KSH 1,000","KSH 1,000 - 3,000","KSH 3,000 - 5,000","KSH 5,000 - 10,000","Over KSH 10,000"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Online Shopping Preferences' LIMIT 1), 'How satisfied are you with overall delivery services in Kenya?', '{"Very satisfied","Satisfied","Neutral","Dissatisfied","Very dissatisfied"}', 8),

((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'How many apps do you download per month on average?', '{"0-2 apps","3-5 apps","6-10 apps","More than 10 apps"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'Which category of apps do you use most frequently?', '{"Social Media & Communication","Fintech & Mobile Money","Shopping & E-commerce","Entertainment & Gaming","Productivity & Education"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'What makes you uninstall a mobile app?', '{"Too many ads","Takes up too much storage","Slow performance/Bugs","Privacy concerns","Difficult navigation"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'Have you ever made in-app purchases?', '{"Yes, frequently","Yes, occasionally","Rarely","Never"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'Do you prefer dark mode or light mode on mobile apps?', '{"Dark mode","Light mode","Follow system settings","Don''t care"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'How do you discover new apps?', '{"Google Play / App Store recommendations","Social media ads","Friends & Family referrals","Tech blogs/Reviews"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'How important are app ratings and reviews before downloading?', '{"Extremely important","Moderately important","Slightly important","Not important"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Mobile App Experience' LIMIT 1), 'Are you comfortable granting location access to non-navigation apps?', '{"Yes, always","Only when app is active","No, rarely","Never"}', 8),

((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'Besides M-Pesa, which other payment service do you use?', '{"Airtel Money","Bank Mobile App (Equity Eazzy, KCB, etc.)","PesaLink","Credit/Debit Card","Crypto / Web3 Wallet"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'How often do you make contactless or QR code payments?', '{"Daily","Multiple times a week","Rarely","Never"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'What is your preferred method for paying utility bills (electricity, water, internet)?', '{"M-Pesa Paybill/Till","Bank app","Service provider app","USSD code","Physical agent"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'Have you ever experienced payment delay or system downtime during a purchase?', '{"Yes, frequently","Yes, a few times","Rarely","Never"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'How secure do you feel using mobile banking apps in Kenya?', '{"Very secure","Somewhat secure","Neutral","Insecure","Very insecure"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'Do you use mobile loans or digital credit services (e.g. Fuliza, Tala, Branch)?', '{"Frequently","Occasionally","Used to, but stopped","Never used"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'What feature would improve your digital payment experience most?', '{"Lower transaction fees","Faster refund process","Better offline support","Enhanced security features","Higher daily limits"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Digital Payment Methods' LIMIT 1), 'Do you keep track of your digital transaction expenses using an app?', '{"Yes, dedicated tracking app","Yes, Excel/Notes","No, just check bank/M-Pesa SMS","No tracking at all"}', 8),

((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'Do you currently invest money in any asset class?', '{"Yes","No, but planning to","No interest"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'Which investment options are you most familiar with?', '{"Money Market Funds (MMFs)","Sacco Shares","Real Estate / Land","Stock Market (NSE)","Cryptocurrency / Forex"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'What is your primary investment goal?', '{"Capital growth","Emergency savings","Retirement funding","Passive income","Buying land/property"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'How much risk are you comfortable taking with your savings?', '{"High risk for high returns","Moderate risk","Low risk / Capital preservation","Zero risk only"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'What is the main obstacle preventing you from investing more?', '{"Lack of surplus funds","Lack of financial knowledge","Fear of losing money / Scams","Complex registration procedures"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'Where do you get financial and investment advice?', '{"Financial advisors","Social media / YouTube / X","Friends & Family","Books & Financial blogs","No advice"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'Do you use digital investment platforms (e.g. Mali, Ndovu, Ziidi, MansaX)?', '{"Yes, currently active","Tried before","Aware, but not using","Never heard of them"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Investment Awareness' LIMIT 1), 'How monthly contribution would you start an investment with?', '{"Under KSH 1,000","KSH 1,000 - 3,000","KSH 3,000 - 5,000","KSH 5,000 - 10,000","Above KSH 10,000"}', 8),

((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'What tech device do you plan to purchase next?', '{"Smartphone","Laptop / PC","Smartwatch / Fitness tracker","Tablet","Smart TV / Streaming device"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'How often do you upgrade your primary smartphone?', '{"Every year","Every 2 years","Every 3-4 years","Only when broken"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'Do you own or use wearable technology (e.g. Smartwatch, Earbuds)?', '{"Yes, both smartwatch and wireless earbuds","Only wireless earbuds","Only smartwatch","Neither"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'Where do you purchase your electronic gadgets?', '{"Official brand store","Local electronics shop","Online store (Jumia, Kilimall, etc.)","Refurbished/Second-hand dealer"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'What factor is most crucial when selecting a smartphone?', '{"Battery life","Camera quality","Storage capacity & RAM","Price / Value for money","Brand reputation"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'Have you used Smart Home devices (e.g., smart bulbs, security cameras, smart plugs)?', '{"Yes, extensive setup","Yes, 1-2 devices","No, but interested","No interest"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'How do you handle old electronics you no longer use?', '{"Keep at home / Store away","Sell as second-hand","Give away to family/friends","E-waste recycling"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Tech Gadget Usage' LIMIT 1), 'How much total budget do you allocate annually for tech gadgets?', '{"Under KSH 10,000","KSH 10,000 - 30,000","KSH 30,000 - 60,000","KSH 60,000 - 100,000","Over KSH 100,000"}', 8);

-- ------------------------------------------------------------------------------
-- 9. SEED DATA - SILVER PLUS SURVEYS & QUESTIONS
-- ------------------------------------------------------------------------------
INSERT INTO public.surveys (title, category, category_id, reward, duration, questions_count, is_active, created_at) VALUES
('Health & Fitness Habits', 'Health', 'silver_plus', 200, '5 min', 10, true, NOW()),
('Mental Wellness Survey', 'Health', 'silver_plus', 200, '4 min', 10, true, NOW()),
('Lifestyle & Daily Routine', 'Lifestyle', 'silver_plus', 200, '5 min', 10, true, NOW()),
('Fashion & Style Preferences', 'Lifestyle', 'silver_plus', 200, '4 min', 10, true, NOW()),
('Wellness & Self-Care', 'Health', 'silver_plus', 200, '5 min', 10, true, NOW());

-- Questions for Silver Plus Surveys
INSERT INTO public.survey_questions (survey_id, question_text, options, question_order) VALUES
((SELECT id FROM public.surveys WHERE title = 'Health & Fitness Habits' LIMIT 1), 'How often do you exercise weekly?', '{"Daily","3-5 times a week","1-2 times a week","Rarely","Never"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Health & Fitness Habits' LIMIT 1), 'What type of physical activity do you engage in most?', '{"Gym / Weightlifting","Jogging / Running","Walking","Home workouts","Sports (Football, Basketball, etc.)"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Health & Fitness Habits' LIMIT 1), 'Do you use fitness tracking apps or wearables?', '{"Yes, smartwatch/tracker","Yes, smartphone app","No, but considering","No"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Health & Fitness Habits' LIMIT 1), 'How many liters of water do you drink daily on average?', '{"Less than 1 liter","1-2 liters","2-3 liters","More than 3 liters"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Health & Fitness Habits' LIMIT 1), 'Do you follow a specific dietary plan?', '{"No specific diet","Low carb / Keto","Vegetarian / Vegan","High protein","Intermittent fasting"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Health & Fitness Habits' LIMIT 1), 'How many hours of sleep do you get per night?', '{"Under 5 hours","5-6 hours","7-8 hours","More than 8 hours"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Health & Fitness Habits' LIMIT 1), 'Do you take dietary supplements or vitamins regularly?', '{"Yes, daily","Occasionally","Only when prescribed","Never"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Health & Fitness Habits' LIMIT 1), 'What is your primary fitness objective?', '{"Weight loss","Muscle building","Endurance & Stamina","General wellbeing & Stress reduction"}', 8),
((SELECT id FROM public.surveys WHERE title = 'Health & Fitness Habits' LIMIT 1), 'How much money do you spend monthly on health & fitness (gym, organic food, supplements)?', '{"Under KSH 1,000","KSH 1,000 - 3,000","KSH 3,000 - 5,000","Over KSH 5,000"}', 9),
((SELECT id FROM public.surveys WHERE title = 'Health & Fitness Habits' LIMIT 1), 'How would you rate your overall physical health condition?', '{"Excellent","Good","Average","Needs improvement"}', 10),

((SELECT id FROM public.surveys WHERE title = 'Mental Wellness Survey' LIMIT 1), 'How often do you feel stressed due to work or financial pressure?', '{"Daily","Frequently","Occasionally","Rarely","Never"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Mental Wellness Survey' LIMIT 1), 'What is your primary method for relieving stress?', '{"Physical exercise","Listening to music / Podcasts","Spending time with friends/family","Meditation / Breathing exercises","Sleeping"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Mental Wellness Survey' LIMIT 1), 'Have you ever used or considered therapy or mental wellness counseling?', '{"Currently in therapy","Tried before","Open to it","Not interested"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Mental Wellness Survey' LIMIT 1), 'How easily do you disconnect from work/phone during downtime?', '{"Very easily","Somewhat easily","With difficulty","Almost impossible"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Mental Wellness Survey' LIMIT 1), 'Do you practice mindfulness or journaling?', '{"Yes, daily practice","Occasionally","Tried, but stopped","Never tried"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Mental Wellness Survey' LIMIT 1), 'How does social media affect your mood generally?', '{"Positively / Inspiring","Neutral","Negatively / Causes anxiety","Varies depending on usage"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Mental Wellness Survey' LIMIT 1), 'Do you feel comfortable discussing mental health with peers or family in Kenya?', '{"Very comfortable","Moderately comfortable","Slightly uncomfortable","Not comfortable at all"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Mental Wellness Survey' LIMIT 1), 'How often do you take mental health breaks or personal days?', '{"Regularly","A few times a year","Rarely","Never"}', 8),
((SELECT id FROM public.surveys WHERE title = 'Mental Wellness Survey' LIMIT 1), 'Would you use an online mental wellness app tailored for Africans?', '{"Yes, definitely","Maybe","Unlikely","No"}', 9),
((SELECT id FROM public.surveys WHERE title = 'Mental Wellness Survey' LIMIT 1), 'Overall, how content do you feel with your work-life balance?', '{"Extremely content","Moderately content","Slightly discontent","Very discontent"}', 10),

((SELECT id FROM public.surveys WHERE title = 'Lifestyle & Daily Routine' LIMIT 1), 'What time do you usually start your daily routine?', '{"Before 5:00 AM","5:00 AM - 6:30 AM","6:30 AM - 8:00 AM","After 8:00 AM"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Lifestyle & Daily Routine' LIMIT 1), 'How do you spend your morning hours primarily?', '{"Exercise & Meditation","Preparing for work/school","Social media & News","Household chores"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Lifestyle & Daily Routine' LIMIT 1), 'How many hours a day do you spend sitting or sedentary?', '{"Less than 4 hours","4-7 hours","7-10 hours","More than 10 hours"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Lifestyle & Daily Routine' LIMIT 1), 'What is your main hobby outside work?', '{"Sports & Outdoor activities","Reading & Learning","Gaming","Cooking & Baking","Creative arts (Music, Drawing, Writing)"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Lifestyle & Daily Routine' LIMIT 1), 'How often do you socialize with friends outside your home?', '{"Multiple times a week","Once a week","1-2 times a month","Rarely"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Lifestyle & Daily Routine' LIMIT 1), 'Do you manage a daily or weekly to-do list?', '{"Yes, digital app","Yes, notebook/paper","In my head","No planning"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Lifestyle & Daily Routine' LIMIT 1), 'How often do you travel outside your hometown for leisure?', '{"Monthly","Quarterly","Once or twice a year","Rarely"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Lifestyle & Daily Routine' LIMIT 1), 'Where do you spend most weekend leisure time?', '{"At home with family","Outdoors / Nature parks","Restaurants / Lounges","Shopping malls / Events"}', 8),
((SELECT id FROM public.surveys WHERE title = 'Lifestyle & Daily Routine' LIMIT 1), 'Do you feel you have enough free time for personal interests?', '{"More than enough","Just enough","Insufficient","Almost none"}', 9),
((SELECT id FROM public.surveys WHERE title = 'Lifestyle & Daily Routine' LIMIT 1), 'How satisfied are you with your current daily routine?', '{"Very satisfied","Satisfied","Neutral","Needs major changes"}', 10),

((SELECT id FROM public.surveys WHERE title = 'Fashion & Style Preferences' LIMIT 1), 'Where do you buy most of your clothing?', '{"Local boutiques / Malls","Boutiques & Mitumba (Second-hand)","Online stores / Instagram vendors","Custom tailors","International brands"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Fashion & Style Preferences' LIMIT 1), 'How often do you purchase new apparel?', '{"Monthly","Every 2-3 months","Twice a year","Only during special occasions"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Fashion & Style Preferences' LIMIT 1), 'What influences your personal fashion style most?', '{"Comfort & Utility","Current social media trends","Workplace requirements","Celebrities / Influencers","Personal unique taste"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Fashion & Style Preferences' LIMIT 1), 'What is your average monthly spend on clothing and footwear?', '{"Under KSH 1,500","KSH 1,500 - 3,500","KSH 3,500 - 7,000","Over KSH 7,000"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Fashion & Style Preferences' LIMIT 1), 'Do you prefer fast fashion or sustainable/durable apparel?', '{"Fast fashion (Trend focused)","Sustainable & Durable","Mix of both","Don''t pay attention"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Fashion & Style Preferences' LIMIT 1), 'Which accessory do you invest in most?', '{"Shoes & Sneakers","Handbags / Backpacks","Watches & Jewelry","Eyewear / Sunglasses"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Fashion & Style Preferences' LIMIT 1), 'Have you bought footwear or clothes online in Kenya?', '{"Yes, frequently","Tried a few times","No, prefer fitting in person"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Fashion & Style Preferences' LIMIT 1), 'How important is brand name when purchasing fashion items?', '{"Very important","Somewhat important","Not important at all"}', 8),
((SELECT id FROM public.surveys WHERE title = 'Fashion & Style Preferences' LIMIT 1), 'Do you support local Kenyan fashion designers / Made-in-Kenya brands?', '{"Yes, actively purchase","Aware, but rarely buy","Not familiar with any"}', 9),
((SELECT id FROM public.surveys WHERE title = 'Fashion & Style Preferences' LIMIT 1), 'How would you describe your overall personal aesthetic?', '{"Casual & Comfy","Formal & Smart","Trendy & Streetwear","Minimalist","Eclectic"}', 10),

((SELECT id FROM public.surveys WHERE title = 'Wellness & Self-Care' LIMIT 1), 'How often do you dedicate time exclusively for personal self-care?', '{"Daily","Weekly","Bi-weekly","Monthly","Rarely"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Wellness & Self-Care' LIMIT 1), 'What self-care routine do you value most?', '{"Skincare & Grooming","Spa / Massage treatments","Quiet reading time","Digital detox","Healthy meal prep"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Wellness & Self-Care' LIMIT 1), 'How much do you spend monthly on skincare and grooming products?', '{"Under KSH 1,000","KSH 1,000 - 2,500","KSH 2,500 - 5,000","Over KSH 5,000"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Wellness & Self-Care' LIMIT 1), 'Do you prefer natural/organic beauty and wellness products?', '{"Always natural","Prefer natural when possible","Don''t mind synthetic","Not sure"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Wellness & Self-Care' LIMIT 1), 'Where do you get self-care recommendations?', '{"Dermatologist / Specialists","TikTok / YouTube creators","Friends & Family","Product reviews"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Wellness & Self-Care' LIMIT 1), 'How often do you visit a spa or professional salon/barbershop?', '{"Weekly","Bi-weekly","Monthly","Quarterly or less"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Wellness & Self-Care' LIMIT 1), 'Do you practice herbal medicine or aromatherapy for relaxation?', '{"Yes, regularly","Occasionally","Tried before","Never"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Wellness & Self-Care' LIMIT 1), 'What is your top barrier to practicing regular self-care?', '{"Busy schedule / Lack of time","Cost of products/services","Lack of knowledge","Low priority"}', 8),
((SELECT id FROM public.surveys WHERE title = 'Wellness & Self-Care' LIMIT 1), 'Do you track your daily mood or energy levels?', '{"Yes, via app","Yes, in a diary","Mentally aware","No tracking"}', 9),
((SELECT id FROM public.surveys WHERE title = 'Wellness & Self-Care' LIMIT 1), 'How would you rate your overall wellbeing satisfaction right now?', '{"Very satisfied","Satisfied","Neutral","Unsatisfied"}', 10);

-- ------------------------------------------------------------------------------
-- 10. SEED DATA - GOLD PLUS SURVEYS & QUESTIONS
-- ------------------------------------------------------------------------------
INSERT INTO public.surveys (title, category, category_id, reward, duration, questions_count, is_active, created_at) VALUES
('Entertainment & Streaming Habits', 'Entertainment', 'gold_plus', 250, '6 min', 12, true, NOW()),
('Gaming & Esports Interest', 'Entertainment', 'gold_plus', 250, '5 min', 12, true, NOW()),
('Online Learning & Courses', 'Education', 'gold_plus', 250, '6 min', 12, true, NOW()),
('Career Development & Skills', 'Education', 'gold_plus', 250, '5 min', 12, true, NOW()),
('Social Media & Content Creation', 'Entertainment', 'gold_plus', 250, '6 min', 12, true, NOW());

-- Questions for Gold Plus Surveys
INSERT INTO public.survey_questions (survey_id, question_text, options, question_order) VALUES
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Streaming Habits' LIMIT 1), 'Which video streaming service do you use most?', '{"Netflix","Showmax","YouTube / YouTube Premium","Amazon Prime Video","Local TV Apps (Citizen Digital, etc.)"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Streaming Habits' LIMIT 1), 'How many streaming subscriptions do you currently pay for?', '{"0 (Use free/Shared)","1 service","2 services","3 or more services"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Streaming Habits' LIMIT 1), 'What is your primary music streaming platform?', '{"Spotify","Apple Music","Boomplay","YouTube Music","Audiomack"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Streaming Habits' LIMIT 1), 'How much total money do you spend on video & music streaming monthly?', '{"Under KSH 500","KSH 500 - 1,500","KSH 1,500 - 3,000","Over KSH 3,000"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Streaming Habits' LIMIT 1), 'How do you access streaming content?', '{"Home Wi-Fi","Mobile Data Bundles","Office / Public Wi-Fi","Downloaded for offline viewing"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Streaming Habits' LIMIT 1), 'What genre of movies or TV shows do you watch most frequently?', '{"Action & Thriller","Drama & Romance","Comedy","Documentaries & True Crime","Sci-Fi & Fantasy"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Streaming Habits' LIMIT 1), 'Do you watch African / Kenyan produced films and series?', '{"Yes, regularly","Occasionally","Rarely","Never"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Streaming Habits' LIMIT 1), 'How often do you go to a cinema theater?', '{"Monthly or more","Every few months","Once a year","Never"}', 8),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Streaming Habits' LIMIT 1), 'Do you listen to podcasts?', '{"Yes, daily","A few times a week","Rarely","Never"}', 9),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Streaming Habits' LIMIT 1), 'What device do you use most for video entertainment?', '{"Smartphone","Smart TV","Laptop / Desktop","Tablet"}', 10),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Streaming Habits' LIMIT 1), 'How important is high resolution (4K / Full HD) streaming to you?', '{"Crucial","Somewhat important","Not important as long as it plays"}', 11),
((SELECT id FROM public.surveys WHERE title = 'Entertainment & Streaming Habits' LIMIT 1), 'Would you accept ad-supported cheaper streaming plans?', '{"Yes, definitely","Maybe","No, prefer ad-free"}', 12),

((SELECT id FROM public.surveys WHERE title = 'Gaming & Esports Interest' LIMIT 1), 'On which platform do you play games most often?', '{"Mobile phone (Android/iOS)","PlayStation / Xbox console","PC / Laptop","Handheld console (Nintendo Switch)","Don''t play games"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Gaming & Esports Interest' LIMIT 1), 'How many hours per week do you spend playing games?', '{"Under 2 hours","2-5 hours","5-10 hours","More than 10 hours"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Gaming & Esports Interest' LIMIT 1), 'What genre of video games do you prefer?', '{"Sports (FC/FIFA, eFootball)","Action / Battle Royale (PUBG, COD)","Puzzle / Casual (Candy Crush)","Racing (Need for Speed, Asphalt)","Strategy / RPG"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Gaming & Esports Interest' LIMIT 1), 'Have you ever spent money on in-game purchases (skins, battle passes, coins)?', '{"Yes, frequently","Yes, occasionally","No, never"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Gaming & Esports Interest' LIMIT 1), 'Do you follow Esports competitions or gaming streamers?', '{"Yes, watch regularly on Twitch/YouTube","Occasionally","No interest"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Gaming & Esports Interest' LIMIT 1), 'Do you visit video gaming lounges or cyber cafés to play console games in Kenya?', '{"Yes, frequently","Occasionally","Used to, but stopped","Never"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Gaming & Esports Interest' LIMIT 1), 'Would you participate in a local Kenyan Esports tournament for cash prizes?', '{"Yes, definitely","Maybe","No"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Gaming & Esports Interest' LIMIT 1), 'What is your monthly gaming expense (game purchases, data, subscriptions)?', '{"KSH 0 (Free to play)","Under KSH 1,000","KSH 1,000 - 3,000","Over KSH 3,000"}', 8),
((SELECT id FROM public.surveys WHERE title = 'Gaming & Esports Interest' LIMIT 1), 'Do you play multiplayer games online with friends?', '{"Yes, always","Sometimes","No, single-player only"}', 9),
((SELECT id FROM public.surveys WHERE title = 'Gaming & Esports Interest' LIMIT 1), 'How do you rate mobile gaming graphics performance on your phone?', '{"Excellent","Good","Laggy / Needs upgrade"}', 10),
((SELECT id FROM public.surveys WHERE title = 'Gaming & Esports Interest' LIMIT 1), 'Have you heard of web3 or crypto play-to-earn games?', '{"Yes, played them","Heard of them","Never heard of them"}', 11),
((SELECT id FROM public.surveys WHERE title = 'Gaming & Esports Interest' LIMIT 1), 'Overall, how would you classify your gaming identity?', '{"Hardcore gamer","Casual gamer","Social gamer","Non-gamer"}', 12),

((SELECT id FROM public.surveys WHERE title = 'Online Learning & Courses' LIMIT 1), 'Have you taken an online course in the last 12 months?', '{"Yes, completed at least one","Enrolled, but didn''t finish","No, but planning to","No interest"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Online Learning & Courses' LIMIT 1), 'Which online learning platform do you prefer?', '{"Coursera / edX","Udemy","YouTube Tutorials","LinkedIn Learning","Local university portal"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Online Learning & Courses' LIMIT 1), 'What field of study are you most interested in acquiring online?', '{"Coding / Software Development","Data Science & AI","Digital Marketing & Business","Design & UI/UX","Languages & Soft Skills"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Online Learning & Courses' LIMIT 1), 'What is your primary motivation for taking online courses?', '{"Career advancement / Promotion","Finding a new job","Personal interest / Curiosity","Starting a business"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Online Learning & Courses' LIMIT 1), 'How much are you willing to pay for a certified online short course?', '{"Free only","Under KSH 2,000","KSH 2,000 - 5,000","KSH 5,000 - 15,000","Over KSH 15,000"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Online Learning & Courses' LIMIT 1), 'What is your biggest challenge when studying online?', '{"High data costs / Unstable internet","Lack of self-discipline / Time","Lack of practical guidance","Unaffordable certificates"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Online Learning & Courses' LIMIT 1), 'Do employers in Kenya value online course certificates according to you?', '{"Highly valued","Somewhat valued","Not valued compared to degree","Unsure"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Online Learning & Courses' LIMIT 1), 'What course format works best for your schedule?', '{"Self-paced video modules","Live interactive Zoom classes","Text-based tutorials & assignments","Short micro-lessons"}', 8),
((SELECT id FROM public.surveys WHERE title = 'Online Learning & Courses' LIMIT 1), 'How many hours per week can you commit to online learning?', '{"1-3 hours","4-7 hours","8-12 hours","More than 12 hours"}', 9),
((SELECT id FROM public.surveys WHERE title = 'Online Learning & Courses' LIMIT 1), 'Do you prefer learning on a mobile phone or computer?', '{"Laptop / Desktop","Mobile phone","Tablet","Equal mix"}', 10),
((SELECT id FROM public.surveys WHERE title = 'Online Learning & Courses' LIMIT 1), 'Would you join a virtual peer study group for motivation?', '{"Yes, definitely","Maybe","No, prefer solo"}', 11),
((SELECT id FROM public.surveys WHERE title = 'Online Learning & Courses' LIMIT 1), 'How satisfied are you with the quality of free educational content online?', '{"Very satisfied","Satisfied","Neutral","Dissatisfied"}', 12),

((SELECT id FROM public.surveys WHERE title = 'Career Development & Skills' LIMIT 1), 'What is your current employment status?', '{"Employed full-time","Self-employed / Entrepreneur","Freelancer / Gig worker","Student","Job seeker"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Career Development & Skills' LIMIT 1), 'How actively are you seeking new career opportunities right now?', '{"Actively applying","Open to good offers","Not looking","Planning to start a business"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Career Development & Skills' LIMIT 1), 'Which platform do you use most for professional networking and job search?', '{"LinkedIn","BrighterMonday / Fuzu","Twitter / X","Word of mouth / Referrals"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Career Development & Skills' LIMIT 1), 'What skill do you feel is most essential for career growth in Kenya today?', '{"Digital & Tech literacy","Data analysis","Sales & Negotiation","Leadership & Management","Foreign languages"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Career Development & Skills' LIMIT 1), 'Have you ever attended career webinars, networking events, or workshops?', '{"Attended many","Attended a few","Never attended"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Career Development & Skills' LIMIT 1), 'How often do you update your resume / CV and LinkedIn profile?', '{"Monthly","Every 6 months","Once a year","Only when applying for a job"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Career Development & Skills' LIMIT 1), 'Would you hire a professional CV writer or career coach?', '{"Yes, have used one","Would consider","No, write myself"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Career Development & Skills' LIMIT 1), 'How confident are you in AI tools (like ChatGPT) assisting your work/job?', '{"Very confident / Daily user","Moderately confident","Slightly confident","Do not use AI"}', 8),
((SELECT id FROM public.surveys WHERE title = 'Career Development & Skills' LIMIT 1), 'What is your expected timeline for achieving your next career milestone?', '{"Within 6 months","6-12 months","1-2 years","3+ years"}', 9),
((SELECT id FROM public.surveys WHERE title = 'Career Development & Skills' LIMIT 1), 'Does your employer provide professional development subsidies or training?', '{"Yes, full support","Partial support","No support","N/A"}', 10),
((SELECT id FROM public.surveys WHERE title = 'Career Development & Skills' LIMIT 1), 'How important is remote work flexibility in your career choice?', '{"Mandatory requirement","Highly preferred","Nice to have","Prefer office work"}', 11),
((SELECT id FROM public.surveys WHERE title = 'Career Development & Skills' LIMIT 1), 'Overall, how optimistic are you about your career prospects over the next 3 years?', '{"Extremely optimistic","Moderately optimistic","Neutral","Pessimistic"}', 12),

((SELECT id FROM public.surveys WHERE title = 'Social Media & Content Creation' LIMIT 1), 'Which social media platform do you spend the most time on daily?', '{"TikTok","Instagram","X (formerly Twitter)","Facebook","YouTube"}', 1),
((SELECT id FROM public.surveys WHERE title = 'Social Media & Content Creation' LIMIT 1), 'Do you post or create content publicly on social media?', '{"Yes, active content creator","Post occasionally","Only share/repost","Lurk / Silent consumer"}', 2),
((SELECT id FROM public.surveys WHERE title = 'Social Media & Content Creation' LIMIT 1), 'Have you ever earned income from social media or digital content?', '{"Yes, primary income","Yes, side hustle","No, but interested","No"}', 3),
((SELECT id FROM public.surveys WHERE title = 'Social Media & Content Creation' LIMIT 1), 'What type of content do you consume most on TikTok/Reels?', '{"Comedy & Entertainment","Educational & Tips","Lifestyle & Vlogs","News & Politics","Dance & Music"}', 4),
((SELECT id FROM public.surveys WHERE title = 'Social Media & Content Creation' LIMIT 1), 'How many hours daily do you spend on social media apps combined?', '{"Under 1 hour","1-3 hours","3-5 hours","More than 5 hours"}', 5),
((SELECT id FROM public.surveys WHERE title = 'Social Media & Content Creation' LIMIT 1), 'Have you bought a product based on a influencer recommendation?', '{"Frequently","A few times","Rarely","Never"}', 6),
((SELECT id FROM public.surveys WHERE title = 'Social Media & Content Creation' LIMIT 1), 'What tool do you use for editing mobile photos/videos?', '{"CapCut","Canva","Adobe Lightroom/Premiere","InShot","Built-in phone editor"}', 7),
((SELECT id FROM public.surveys WHERE title = 'Social Media & Content Creation' LIMIT 1), 'Do you use social media for business or brand marketing?', '{"Yes, business page","Yes, personal brand","No"}', 8),
((SELECT id FROM public.surveys WHERE title = 'Social Media & Content Creation' LIMIT 1), 'How concerned are you about privacy and data security on social media?', '{"Extremely concerned","Moderately concerned","Not concerned"}', 9),
((SELECT id FROM public.surveys WHERE title = 'Social Media & Content Creation' LIMIT 1), 'Do you take periodic social media detox breaks?', '{"Regularly","Occasionally","Tried, but failed","Never"}', 10),
((SELECT id FROM public.surveys WHERE title = 'Social Media & Content Creation' LIMIT 1), 'Would you subscribe to a paid content creator (e.g. Patreon/Substack)?', '{"Already subscribing","Would consider","Unlikely","No"}', 11),
((SELECT id FROM public.surveys WHERE title = 'Social Media & Content Creation' LIMIT 1), 'How do you view the impact of social media on society in Kenya?', '{"Mostly positive","Mixed / Neutral","Mostly negative"}', 12);

-- ==============================================================================
-- END OF MIGRATION SCRIPT
-- ==============================================================================
